<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Store extends Model
{
    private const DEFAULT_VARIANT_ID = 'default';

    protected $attributes = [
        'slug' => '',
        'currency' => 'USD',
        'root_sections' => '{}',
        'custom_sections' => '{}',
    ];

    protected $fillable = [
        'currency', 'slug',
    ];
    protected $casts = [
        'root_sections' => 'array',
        'custom_sections' => 'array',
        'id' => 'integer',
        'user_id' => 'integer',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub


        static::creating(function (Store $store) {
            $store->filterRootSections();
        });
        static::saving(function (Store $store) {
            $store->filterRootSections();
        });
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function getConfirmedAttribute()
    {
        return $this->user->confirmed;
    }

    public function getProductsAttribute()
    {
        return $this->user->products;
    }

    /**
     * Adds the missing parameters and the missing sections in the root sections.
     * If a parameter is missing, the default value is given.
     *
     * If an invalid parameter still exists, it is ignored, not deleted, in order
     * to avoid data loss during migration.
     *
     * This method is called upon creation and saving of the store.
     */
    public function filterRootSections()
    {
        $rootSections = array_merge([], $this->root_sections);
        foreach ($this->rootSectionsInfo as $sectionId => $sectionInfo) {
            if (!array_key_exists($sectionId, $rootSections)) {
                $rootSections[$sectionId] = [];
            }

            if (!array_key_exists('variant', $rootSections[$sectionId])) {
                $variant = self::DEFAULT_VARIANT_ID;
                $rootSections[$sectionId]['variant'] = $variant;
            } else {
                $variant = $rootSections[$sectionId]['variant'];
            }

            $variantInfo = $sectionInfo['variants'][$variant];
            foreach ($variantInfo['parameters'] as $parameterId => $parameterInfo) {
                if (!array_key_exists($sectionId, $this->root_sections)
                    || !array_key_exists('parameters', $this->root_sections[$sectionId])
                    || !array_key_exists($parameterId, $this->root_sections[$sectionId]['parameters'])) {
                    $rootSections[$sectionId]['parameters'][$parameterId] = $parameterInfo['default'];
                }
            }
        }
        $this->root_sections = $rootSections;
    }

    /**
     * Generates the validation rules for every root section parameter.
     * The following constraints are added to the rules:
     * - Minimum
     * - Maximum
     * - Regular expression matching
     *
     * @param array|null $rootSections The root sections to be validated.
     * @return array The rules array associated to each parameter.
     */
    public function getRootSectionsRules(?array $rootSections)
    {
        $field = 'root_sections';
        $parametersTypes = $this->getParametersTypes();

        $rules = [];
        $rules[$field] = ['array'];

        if ($rootSections === null)
            return $rules;

        foreach ($this->rootSectionsInfo as $sectionId => $sectionInfo) {
            $variantField = sprintf("%s.%s.variant", $field, $sectionId);
            $rules[$variantField] = 'in:' . implode(',', array_keys($sectionInfo['variants']));
            if (array_key_exists($sectionId, $rootSections)
                and array_key_exists('variant', $rootSections[$sectionId])) {
                $variant = $rootSections[$sectionId]['variant'];
                if (array_key_exists($variant, $sectionInfo['variants'])) {
                    $variantInfo = $sectionInfo['variants'][$variant];
                    foreach ($variantInfo['parameters'] as $parameterId => $parameterInfo) {
                        $ruleField = sprintf('%s.%s.parameters.%s', $field, $sectionId, $parameterId);
                        $rules[$ruleField] = $parametersTypes[$parameterInfo['type']]['rules'];

                        if (array_key_exists('min', $parameterInfo))
                            $rules[$ruleField][] = 'min:' . $parameterInfo['min'];

                        if (array_key_exists('max', $parameterInfo))
                            $rules[$ruleField][] = 'max:' . $parameterInfo['max'];

                        if (array_key_exists('regex', $parameterInfo))
                            $rules[$ruleField][] = 'regex:' . $parameterInfo['regex'];
                    }
                }
            }
        }

        return $rules;
    }

    public function getParametersTypes()
    {
        return [
            'rgb' => [
                'rules' => ['rgb'],
            ],
            'rgba' => [
                'rules' => ['rgba'],
            ],
            'link' => [
                'rules' => ['url'],
            ],
            'asset' => [
                'rules' => ['url'],
            ],
            'text' => [
                'rules' => ['string'],
            ],
            'boolean' => [
                'rules' => ['boolean'],
            ],
        ];
    }

    public function getRootSectionsInfoAttribute()
    {
        $publicStorageUrl = config('app.backend_url') . '/storage/';
        return [
            'general' => [
                'name' => 'General Settings',
                'description' => 'Change the general look of your store',
                'icon' => 'mdi-brush',
                'variants' => [
                    'default' => [
                        'name' => 'Default',
                        'parameters' => [
                            'name' => [
                                'name' => 'Store Name',
                                'type' => 'text',
                                'default' => 'My Store',
                                'min' => 3,
                                'max' => 40,
                            ],
                            'tagline' => [
                                'name' => 'Store Tagline',
                                'type' => 'text',
                                'default' => 'Welcome!',
                                'max' => 40,
                            ],
                            'logo' => [
                                'name' => 'Logo',
                                'type' => 'asset',
                                'default' => $publicStorageUrl . 'prevu-logo-small.png',
                            ],
                            'primary_color' => [
                                'name' => 'Primary Color',
                                'type' => 'rgb',
                                'default' => 'rgb(255, 255, 255)',
                            ],
                            'secondary_color' => [
                                'name' => 'Secondary Color',
                                'type' => 'rgb',
                                'default' => 'rgb(243, 243, 243)',
                            ],
                            'tertiary_color' => [
                                'name' => 'Tertiary Color',
                                'type' => 'rgb',
                                'default' => 'rgb(81, 98, 141)',
                            ],
                        ],
                    ],
                ],
            ],
            'media_links' => [
                'name' => 'Social Media Links',
                'description' => 'Set the links to your different social media accounts for your visitors to easily find you everywhere',
                'icon' => 'mdi-share-variant',
                'variants' => [
                    'default' => [
                        /*
                         * Many regex are taken from: https://github.com/lorey/social-media-profiles-regexs
                         */
                        'name' => 'Default',
                        'parameters' => [
                            'personal' => [
                                'name' => 'Personal Website',
                                'example' => 'https://prev-u.com/',
                                'type' => 'link',
                                'regex' => "/^(.*)$/",
                                'default' => '',
                            ],
                            'facebook' => [
                                'name' => 'Facebook Page',
                                'example' => 'https://facebook.com/PrevU.official',
                                'type' => 'link',
                                'regex' => '/^http(s)?:\/\/(www\.)?(facebook|fb)\.com\/[A-z0-9_\-\.]+\/?$/',
                                'default' => '',
                            ],
                            'twitter' => [
                                'name' => 'Twitter Account',
                                'example' => 'https://twitter.com/PrevU',
                                'type' => 'link',
                                'regex' => '/^http(s)?:\/\/(.*\.)?twitter\.com\/[A-z0-9_]+\/?$/',
                                'default' => '',
                            ],
                            'youtube' => [
                                'name' => 'Youtube Channel',
                                'example' => 'https://youtube.com/channel/PrevU',
                                'type' => 'link',
                                'regex' => '/^((http|https):\/\/|)(www\.|)youtube\.com\/(channel\/|user\/)[a-zA-Z0-9\-]{1,}$/',
                                'default' => '',
                            ],
                            'instagram' => [
                                'name' => 'Instagram Page',
                                'example' => 'https://instagram.com/PrevU',
                                'type' => 'link',
                                'regex' => '/^https?:\/\/(www\.)?instagram\.com\/[a-zA-Z0-9\.\_]+\/?$/',
                                'default' => '',
                            ],
                            'linkedin' => [
                                'name' => 'LinkedIn Profile',
                                'example' => 'https://linkedin.com/in/PrevU',
                                'type' => 'link',
                                'regex' => '/^http(s)?:\/\/([\w]+\.)?linkedin\.com\/in\/[A-z0-9_-]+\/?$/',
                                'default' => '',
                            ],
                            'telegram' => [
                                'name' => 'Telegram Page',
                                'example' => 'https://t.me/PrevU',
                                'type' => 'link',
                                'regex' => '/^https?:\/\/(t(elegram)?\.me|telegram\.org)\/([a-z0-9\_]{5,32})\/?$/',
                                'default' => '',
                            ],
                            'soundcloud' => [
                                'name' => 'Soundcloud Page',
                                'example' => 'https://soundcloud.com/PrevU',
                                'type' => 'link',
                                'regex' => '/^https?:\/\/(soundcloud\.com|snd\.sc)\/[A-Za-z0-9][A-Za-z0-9_-]+$/',
                                'default' => '',
                            ],
                        ],
                    ],
                ],
            ],
            'banner' => [
                'name' => 'Banner',
                'description' => 'Change the look of the homepage\'s top banner',
                'icon' => 'mdi-dock-bottom',
                'variants' => [
                    'default' => [
                        'name' => 'Medium',
                        'parameters' => [
                            'image' => [
                                'name' => 'Image',
                                'type' => 'asset',
                                'default' => $publicStorageUrl . 'glitter-lights.jpg',
                            ],
                            'overlay_color' => [
                                'name' => 'Overlay Color',
                                'type' => 'rgba',
                                'default' => 'rgba(0, 0, 0, 0.2)',
                            ],
                            'header' => [
                                'name' => 'Header',
                                'type' => 'text',
                                'default' => 'My Engaging Header',
                                'max' => 35,
                            ],
                            'subheader' => [
                                'name' => 'Subheader',
                                'type' => 'text',
                                'default' => 'My Fantastic Subheader',
                                'max' => 35,
                            ],
                        ],
                    ],
                    'minimal' => [
                        'name' => 'Minimal',
                        'parameters' => [
                            'image' => [
                                'name' => 'Image',
                                'type' => 'asset',
                                'default' => $publicStorageUrl . 'glitter-lights.jpg',
                            ],
                            'overlay_color' => [
                                'name' => 'Overlay Color',
                                'type' => 'rgba',
                                'default' => 'rgba(0, 0, 0, 0.2)',
                            ],
                            'header' => [
                                'name' => 'Header',
                                'type' => 'text',
                                'default' => 'My Engaging Header',
                                'max' => 35,
                            ],
                        ],
                    ],
                    'fullscreen' => [
                        'name' => 'Fullscreen',
                        'parameters' => [
                            'image' => [
                                'name' => 'Image',
                                'type' => 'asset',
                                'default' => $publicStorageUrl . 'glitter-lights.jpg',
                            ],
                            'overlay_color' => [
                                'name' => 'Overlay Color',
                                'type' => 'rgba',
                                'default' => 'rgba(0, 0, 0, 0.2)',
                            ],
                            'header' => [
                                'name' => 'Header',
                                'type' => 'text',
                                'default' => 'My Engaging Header',
                                'max' => 35,
                            ],
                            'subheader' => [
                                'name' => 'Subheader',
                                'type' => 'text',
                                'default' => 'My Fantastic Subheader',
                                'max' => 35,
                            ],
                            'show_button' => [
                                'name' => 'Show Button',
                                'type' => 'boolean',
                                'default' => true,
                            ],
                            'button_text' => [
                                'name' => 'Button Text',
                                'type' => 'text',
                                'default' => 'See my work',
                                'max' => 40,
                            ],
                        ],
                    ],
                ],
            ],
            'nav_bar' => [
                'name' => 'Nav Bar',
                'description' => 'Change the look of the store\'s navigation bar',
                'icon' => 'mdi-navigation',
                'variants' => [
                    'default' => [
                        'name' => 'Simple',
                        'parameters' => [
                            'color' => [
                                'name' => 'Color',
                                'type' => 'rgb',
                                'default' => 'rgb(255, 255, 255)',
                            ],
                            'show_logo' => [
                                'name' => 'Show Logo',
                                'type' => 'boolean',
                                'default' => true,
                            ],
                            'show_name' => [
                                'name' => 'Show Store Name',
                                'type' => 'boolean',
                                'default' => true,
                            ],
                        ],
                    ],
                ],
            ],
        ];
    }
}
